application: bionic-feat-87817
version: 1
runtime: python27
api_version: 1
threadsafe: false
#======== root directory =================
handlers:
- url: /main
  script: main.py
#======== js directory ====================
- url: /js
  static_dir: js

#========= css directory ====================
- url: /css
  static_dir: css
- url: css/index.css
  static_files: index.css
  upload: index.css
#========== templates directory ================
- url: /templates
  static_dir: templates
- url: /templates/index.html
  static_files: index.html
  upload: index.html
#============ class directory =================
- url: /class
  static_dir: class

libraries:
- name: webapp2
  version: "2.5.2"
